homepage: "https://curl.haxx.se/"
language: c++
primary_contact: "zolddouzi"
auto_ccs:
  - "601544762@qq.com"
sanitizers:
  - address
  - undefined
  - memory
architectures:
  - x86_64
  - i386
main_repo: 'git@github.com:601544762/testfuzz.git'
