homepage: "https://curl.haxx.se/"
language: c++
primary_contact: "601544762"
auto_ccs:
  - "601544762@qq.com"
sanitizers:
  - address
  - undefined
  - memory
architectures:
  - x86_64
  - i386
main_repo: 'https://github.com/601544762/testfuzz.git'
